### ISSUE TITLE
Which Zigbee Gateway / USB Stick?

### ISSUE THREAD

**Issue by steckenpferd** [kirovilya/ioBroker.zigbee#2]
Hi,

can you update the readme which Zigbee Gateway or USB Stick I can use with this iobroker Adapter to control all the devices.

Thank you

Thomas

**Comment by steckenpferd** [comment]
Sorry I read it wrong you need a cc2531/cc2530 USB Stick

**Comment by kirovilya** [comment]
Yes, it work with SoC TI cc253x 
Did you read https://github.com/kirovilya/ioBroker.zigbee/wiki ?
