### ISSUE TITLE
Flash verification error offset 0x0000

### ISSUE THREAD

**Issue by balonchiks** [kirovilya/ioBroker.zigbee#3]
Hi, i am able to successfully detect the chip with the cc_info.py command:

```
INFO: Found a CC2531 chip on /dev/cu.wchusbserial14110

Chip information:
      Chip ID : 0xb524
   Flash size : 256 Kb
    Page size : 2 Kb
    SRAM size : 8 Kb
          USB : Yes

Device information:
 IEEE Address : 00124b001202
           PC : 0000

Debug status:
 [ ] CHIP_ERASE_BUSY
 [ ] PCON_IDLE
 [X] CPU_HALTED
 [ ] PM_ACTIVE
 [ ] HALT_STATUS
 [ ] DEBUG_LOCKED
 [X] OSCILLATOR_STABLE
 [ ] STACK_OVERFLOW

Debug config:
 [ ] SOFT_POWER_MODE
 [ ] TIMERS_OFF
 [X] DMA_PAUSE
 [X] TIMER_SUSPEND
```

however, when i flash i got this error:
```
INFO: Found a CC2531 chip on /dev/cu.wchusbserial14110

Chip information:
      Chip ID : 0xb524
   Flash size : 256 Kb
    Page size : 2 Kb
    SRAM size : 8 Kb
          USB : Yes
Sections in CC2531ZNP-Pro-Secure_LinkKeyJoin_mod.hex:

 Addr.    Size
-------- -------------
 0x0000   8176 B 
 0x1ff6   10 B 
 0x3fff0   1 B 
 0x2000   239616 B 

This is going to OVERWRITE the chip. Are you sure? <y/N>:  y

Flashing:
 - Flashing 4 memory blocks...
 -> 0x0000 : 8176 bytes 
    Progress 0%...  ERROR: Flash verification error on offset 0x0000
```

Do you have any idea what can it be? i am flashing a cc2531 module with the arduino nano connected as in the wiki without any transistors.

Thank you!

**Comment by kirovilya** [comment]
Please wait, I'll check it in the evening.
Perhaps there is a bug in the modified code somewhere.

P.S. Speak Russian?

**Comment by balonchiks** [comment]
thanks, да :)

**Comment by kirovilya** [comment]
Телеграм есть? найди меня там https://t.me/goofyk

Вот запустил прошивку:
![flash](https://user-images.githubusercontent.com/8360230/40072721-705cd30e-587d-11e8-995a-4c38a6e86ae1.PNG)

Это конечно не cc2531, а cc2530, но большой разницы нет.
У меня сейчас нет стика, чтобы проверить.

Что еще можно проверить, чем отличаться может:
- код для прошивки взят тут https://github.com/kirovilya/CCLib
- скорость порта в python (файл ccproxy.py) и в arduino-прошивке
- у меня используется python 2.7 (на версии 3.* я не проверял)
- прошиваю в Windows 7
- сейчас я запустил прошивку не в командной строке, а в PyCharm (думаю, это не сильно влияет)

**Comment by kirovilya** [comment]
Решилось добавлением ключа `-e` в команду прошивки. С этим параметром сперва происходит очистка.

**Comment by kirovilya** [comment]
Добавил параметр в инструкцию по прошивке
