### ISSUE TITLE
no batt status for xiaomi RTCGQ11LM

### ISSUE THREAD

**Issue by arteck** [kirovilya/ioBroker.zigbee#4]
paring is ok but i cant see the battery status

corr... no batt status for all my aqara devices

**Comment by kirovilya** [comment]
The battery comes in 1-2 hours after pairing.
If it is not, write which devices did not receive the battery.

I hope you have the latest version of the adapter 0.5.7

**Comment by arteck** [comment]
you're right.. very good job..  xiaomi ->ok
next test hue and the reach....

**Comment by kirovilya** [comment]
If ok, I am close this Issue
