### ISSUE TITLE
light value

### ISSUE THREAD

**Issue by arteck** [kirovilya/ioBroker.zigbee#7]
the light value for gu10 osram par16 50 tw and for hue bulb is wrong
high value must be 100 not 254 

I extended myself the source for the hue and osram devices..
make this plz in your code

**Comment by kirovilya** [comment]
You mean brightness?
It is strange. I have 2 bulb: Ikea and Jiawen. Ikea report 254 - max value for brightness and set it too. Jiawen not report brightness, but set - max value is 254.

**Comment by arteck** [comment]
ok thx. i check this self

**Comment by kirovilya** [comment]
report here after check, please

**Comment by arteck** [comment]
it works
